#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("se.sigcont.android.coffeecalculator.Resource", IsApplication=true)]

namespace se.sigcont.android.coffeecalculator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MaterialDesignHelpers.Resource.Color.material_amber_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_amber_100;
			global::MaterialDesignHelpers.Resource.Color.material_amber_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_amber_200;
			global::MaterialDesignHelpers.Resource.Color.material_amber_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_amber_300;
			global::MaterialDesignHelpers.Resource.Color.material_amber_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_amber_400;
			global::MaterialDesignHelpers.Resource.Color.material_amber_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_amber_50;
			global::MaterialDesignHelpers.Resource.Color.material_amber_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_amber_500;
			global::MaterialDesignHelpers.Resource.Color.material_amber_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_amber_600;
			global::MaterialDesignHelpers.Resource.Color.material_amber_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_amber_700;
			global::MaterialDesignHelpers.Resource.Color.material_amber_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_amber_800;
			global::MaterialDesignHelpers.Resource.Color.material_amber_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_amber_900;
			global::MaterialDesignHelpers.Resource.Color.material_amber_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_amber_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_amber_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_amber_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_amber_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_amber_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_amber_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_amber_accent_700;
			global::MaterialDesignHelpers.Resource.Color.material_blue_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_100;
			global::MaterialDesignHelpers.Resource.Color.material_blue_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_200;
			global::MaterialDesignHelpers.Resource.Color.material_blue_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_300;
			global::MaterialDesignHelpers.Resource.Color.material_blue_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_400;
			global::MaterialDesignHelpers.Resource.Color.material_blue_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_50;
			global::MaterialDesignHelpers.Resource.Color.material_blue_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_500;
			global::MaterialDesignHelpers.Resource.Color.material_blue_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_600;
			global::MaterialDesignHelpers.Resource.Color.material_blue_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_700;
			global::MaterialDesignHelpers.Resource.Color.material_blue_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_800;
			global::MaterialDesignHelpers.Resource.Color.material_blue_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_900;
			global::MaterialDesignHelpers.Resource.Color.material_blue_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_blue_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_blue_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_blue_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_accent_700;
			global::MaterialDesignHelpers.Resource.Color.material_blue_grey_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_grey_100;
			global::MaterialDesignHelpers.Resource.Color.material_blue_grey_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_grey_200;
			global::MaterialDesignHelpers.Resource.Color.material_blue_grey_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_grey_300;
			global::MaterialDesignHelpers.Resource.Color.material_blue_grey_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_grey_400;
			global::MaterialDesignHelpers.Resource.Color.material_blue_grey_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_grey_50;
			global::MaterialDesignHelpers.Resource.Color.material_blue_grey_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_grey_500;
			global::MaterialDesignHelpers.Resource.Color.material_blue_grey_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_grey_600;
			global::MaterialDesignHelpers.Resource.Color.material_blue_grey_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_grey_700;
			global::MaterialDesignHelpers.Resource.Color.material_blue_grey_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_grey_800;
			global::MaterialDesignHelpers.Resource.Color.material_blue_grey_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_blue_grey_900;
			global::MaterialDesignHelpers.Resource.Color.material_brown_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_brown_100;
			global::MaterialDesignHelpers.Resource.Color.material_brown_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_brown_200;
			global::MaterialDesignHelpers.Resource.Color.material_brown_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_brown_300;
			global::MaterialDesignHelpers.Resource.Color.material_brown_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_brown_400;
			global::MaterialDesignHelpers.Resource.Color.material_brown_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_brown_50;
			global::MaterialDesignHelpers.Resource.Color.material_brown_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_brown_500;
			global::MaterialDesignHelpers.Resource.Color.material_brown_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_brown_600;
			global::MaterialDesignHelpers.Resource.Color.material_brown_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_brown_700;
			global::MaterialDesignHelpers.Resource.Color.material_brown_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_brown_800;
			global::MaterialDesignHelpers.Resource.Color.material_brown_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_brown_900;
			global::MaterialDesignHelpers.Resource.Color.material_cyan_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_cyan_100;
			global::MaterialDesignHelpers.Resource.Color.material_cyan_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_cyan_200;
			global::MaterialDesignHelpers.Resource.Color.material_cyan_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_cyan_300;
			global::MaterialDesignHelpers.Resource.Color.material_cyan_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_cyan_400;
			global::MaterialDesignHelpers.Resource.Color.material_cyan_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_cyan_50;
			global::MaterialDesignHelpers.Resource.Color.material_cyan_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_cyan_500;
			global::MaterialDesignHelpers.Resource.Color.material_cyan_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_cyan_600;
			global::MaterialDesignHelpers.Resource.Color.material_cyan_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_cyan_700;
			global::MaterialDesignHelpers.Resource.Color.material_cyan_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_cyan_800;
			global::MaterialDesignHelpers.Resource.Color.material_cyan_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_cyan_900;
			global::MaterialDesignHelpers.Resource.Color.material_cyan_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_cyan_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_cyan_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_cyan_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_cyan_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_cyan_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_cyan_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_cyan_accent_700;
			global::MaterialDesignHelpers.Resource.Color.material_deep_orange_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_orange_100;
			global::MaterialDesignHelpers.Resource.Color.material_deep_orange_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_orange_200;
			global::MaterialDesignHelpers.Resource.Color.material_deep_orange_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_orange_300;
			global::MaterialDesignHelpers.Resource.Color.material_deep_orange_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_orange_400;
			global::MaterialDesignHelpers.Resource.Color.material_deep_orange_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_orange_50;
			global::MaterialDesignHelpers.Resource.Color.material_deep_orange_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_orange_500;
			global::MaterialDesignHelpers.Resource.Color.material_deep_orange_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_orange_600;
			global::MaterialDesignHelpers.Resource.Color.material_deep_orange_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_orange_700;
			global::MaterialDesignHelpers.Resource.Color.material_deep_orange_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_orange_800;
			global::MaterialDesignHelpers.Resource.Color.material_deep_orange_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_orange_900;
			global::MaterialDesignHelpers.Resource.Color.material_deep_orange_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_orange_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_deep_orange_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_orange_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_deep_orange_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_orange_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_deep_orange_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_orange_accent_700;
			global::MaterialDesignHelpers.Resource.Color.material_deep_purple_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_purple_100;
			global::MaterialDesignHelpers.Resource.Color.material_deep_purple_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_purple_200;
			global::MaterialDesignHelpers.Resource.Color.material_deep_purple_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_purple_300;
			global::MaterialDesignHelpers.Resource.Color.material_deep_purple_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_purple_400;
			global::MaterialDesignHelpers.Resource.Color.material_deep_purple_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_purple_50;
			global::MaterialDesignHelpers.Resource.Color.material_deep_purple_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_purple_500;
			global::MaterialDesignHelpers.Resource.Color.material_deep_purple_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_purple_600;
			global::MaterialDesignHelpers.Resource.Color.material_deep_purple_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_purple_700;
			global::MaterialDesignHelpers.Resource.Color.material_deep_purple_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_purple_800;
			global::MaterialDesignHelpers.Resource.Color.material_deep_purple_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_purple_900;
			global::MaterialDesignHelpers.Resource.Color.material_deep_purple_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_purple_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_deep_purple_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_purple_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_deep_purple_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_purple_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_deep_purple_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_deep_purple_accent_700;
			global::MaterialDesignHelpers.Resource.Color.material_green_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_green_100;
			global::MaterialDesignHelpers.Resource.Color.material_green_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_green_200;
			global::MaterialDesignHelpers.Resource.Color.material_green_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_green_300;
			global::MaterialDesignHelpers.Resource.Color.material_green_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_green_400;
			global::MaterialDesignHelpers.Resource.Color.material_green_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_green_50;
			global::MaterialDesignHelpers.Resource.Color.material_green_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_green_500;
			global::MaterialDesignHelpers.Resource.Color.material_green_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_green_600;
			global::MaterialDesignHelpers.Resource.Color.material_green_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_green_700;
			global::MaterialDesignHelpers.Resource.Color.material_green_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_green_800;
			global::MaterialDesignHelpers.Resource.Color.material_green_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_green_900;
			global::MaterialDesignHelpers.Resource.Color.material_green_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_green_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_green_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_green_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_green_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_green_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_green_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_green_accent_700;
			global::MaterialDesignHelpers.Resource.Color.material_grey_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_grey_100;
			global::MaterialDesignHelpers.Resource.Color.material_grey_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_grey_200;
			global::MaterialDesignHelpers.Resource.Color.material_grey_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_grey_300;
			global::MaterialDesignHelpers.Resource.Color.material_grey_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_grey_400;
			global::MaterialDesignHelpers.Resource.Color.material_grey_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_grey_50;
			global::MaterialDesignHelpers.Resource.Color.material_grey_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_grey_500;
			global::MaterialDesignHelpers.Resource.Color.material_grey_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_grey_600;
			global::MaterialDesignHelpers.Resource.Color.material_grey_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_grey_700;
			global::MaterialDesignHelpers.Resource.Color.material_grey_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_grey_800;
			global::MaterialDesignHelpers.Resource.Color.material_grey_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_grey_900;
			global::MaterialDesignHelpers.Resource.Color.material_indigo_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_indigo_100;
			global::MaterialDesignHelpers.Resource.Color.material_indigo_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_indigo_200;
			global::MaterialDesignHelpers.Resource.Color.material_indigo_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_indigo_300;
			global::MaterialDesignHelpers.Resource.Color.material_indigo_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_indigo_400;
			global::MaterialDesignHelpers.Resource.Color.material_indigo_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_indigo_50;
			global::MaterialDesignHelpers.Resource.Color.material_indigo_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_indigo_500;
			global::MaterialDesignHelpers.Resource.Color.material_indigo_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_indigo_600;
			global::MaterialDesignHelpers.Resource.Color.material_indigo_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_indigo_700;
			global::MaterialDesignHelpers.Resource.Color.material_indigo_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_indigo_800;
			global::MaterialDesignHelpers.Resource.Color.material_indigo_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_indigo_900;
			global::MaterialDesignHelpers.Resource.Color.material_indigo_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_indigo_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_indigo_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_indigo_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_indigo_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_indigo_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_indigo_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_indigo_accent_700;
			global::MaterialDesignHelpers.Resource.Color.material_light_black = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_black;
			global::MaterialDesignHelpers.Resource.Color.material_light_blue_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_blue_100;
			global::MaterialDesignHelpers.Resource.Color.material_light_blue_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_blue_200;
			global::MaterialDesignHelpers.Resource.Color.material_light_blue_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_blue_300;
			global::MaterialDesignHelpers.Resource.Color.material_light_blue_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_blue_400;
			global::MaterialDesignHelpers.Resource.Color.material_light_blue_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_blue_50;
			global::MaterialDesignHelpers.Resource.Color.material_light_blue_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_blue_500;
			global::MaterialDesignHelpers.Resource.Color.material_light_blue_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_blue_600;
			global::MaterialDesignHelpers.Resource.Color.material_light_blue_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_blue_700;
			global::MaterialDesignHelpers.Resource.Color.material_light_blue_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_blue_800;
			global::MaterialDesignHelpers.Resource.Color.material_light_blue_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_blue_900;
			global::MaterialDesignHelpers.Resource.Color.material_light_blue_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_blue_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_light_blue_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_blue_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_light_blue_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_blue_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_light_blue_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_blue_accent_700;
			global::MaterialDesignHelpers.Resource.Color.material_light_green_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_green_100;
			global::MaterialDesignHelpers.Resource.Color.material_light_green_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_green_200;
			global::MaterialDesignHelpers.Resource.Color.material_light_green_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_green_300;
			global::MaterialDesignHelpers.Resource.Color.material_light_green_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_green_400;
			global::MaterialDesignHelpers.Resource.Color.material_light_green_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_green_50;
			global::MaterialDesignHelpers.Resource.Color.material_light_green_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_green_500;
			global::MaterialDesignHelpers.Resource.Color.material_light_green_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_green_600;
			global::MaterialDesignHelpers.Resource.Color.material_light_green_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_green_700;
			global::MaterialDesignHelpers.Resource.Color.material_light_green_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_green_800;
			global::MaterialDesignHelpers.Resource.Color.material_light_green_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_green_900;
			global::MaterialDesignHelpers.Resource.Color.material_light_green_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_green_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_light_green_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_green_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_light_green_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_green_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_light_green_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_green_accent_700;
			global::MaterialDesignHelpers.Resource.Color.material_light_white = global::se.sigcont.android.coffeecalculator.Resource.Color.material_light_white;
			global::MaterialDesignHelpers.Resource.Color.material_lime_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_lime_100;
			global::MaterialDesignHelpers.Resource.Color.material_lime_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_lime_200;
			global::MaterialDesignHelpers.Resource.Color.material_lime_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_lime_300;
			global::MaterialDesignHelpers.Resource.Color.material_lime_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_lime_400;
			global::MaterialDesignHelpers.Resource.Color.material_lime_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_lime_50;
			global::MaterialDesignHelpers.Resource.Color.material_lime_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_lime_500;
			global::MaterialDesignHelpers.Resource.Color.material_lime_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_lime_600;
			global::MaterialDesignHelpers.Resource.Color.material_lime_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_lime_700;
			global::MaterialDesignHelpers.Resource.Color.material_lime_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_lime_800;
			global::MaterialDesignHelpers.Resource.Color.material_lime_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_lime_900;
			global::MaterialDesignHelpers.Resource.Color.material_lime_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_lime_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_lime_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_lime_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_lime_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_lime_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_lime_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_lime_accent_700;
			global::MaterialDesignHelpers.Resource.Color.material_orange_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_orange_100;
			global::MaterialDesignHelpers.Resource.Color.material_orange_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_orange_200;
			global::MaterialDesignHelpers.Resource.Color.material_orange_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_orange_300;
			global::MaterialDesignHelpers.Resource.Color.material_orange_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_orange_400;
			global::MaterialDesignHelpers.Resource.Color.material_orange_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_orange_50;
			global::MaterialDesignHelpers.Resource.Color.material_orange_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_orange_500;
			global::MaterialDesignHelpers.Resource.Color.material_orange_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_orange_600;
			global::MaterialDesignHelpers.Resource.Color.material_orange_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_orange_700;
			global::MaterialDesignHelpers.Resource.Color.material_orange_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_orange_800;
			global::MaterialDesignHelpers.Resource.Color.material_orange_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_orange_900;
			global::MaterialDesignHelpers.Resource.Color.material_orange_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_orange_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_orange_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_orange_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_orange_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_orange_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_orange_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_orange_accent_700;
			global::MaterialDesignHelpers.Resource.Color.material_pink_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_pink_100;
			global::MaterialDesignHelpers.Resource.Color.material_pink_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_pink_200;
			global::MaterialDesignHelpers.Resource.Color.material_pink_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_pink_300;
			global::MaterialDesignHelpers.Resource.Color.material_pink_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_pink_400;
			global::MaterialDesignHelpers.Resource.Color.material_pink_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_pink_50;
			global::MaterialDesignHelpers.Resource.Color.material_pink_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_pink_500;
			global::MaterialDesignHelpers.Resource.Color.material_pink_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_pink_600;
			global::MaterialDesignHelpers.Resource.Color.material_pink_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_pink_700;
			global::MaterialDesignHelpers.Resource.Color.material_pink_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_pink_800;
			global::MaterialDesignHelpers.Resource.Color.material_pink_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_pink_900;
			global::MaterialDesignHelpers.Resource.Color.material_pink_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_pink_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_pink_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_pink_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_pink_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_pink_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_pink_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_pink_accent_700;
			global::MaterialDesignHelpers.Resource.Color.material_purple_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_purple_100;
			global::MaterialDesignHelpers.Resource.Color.material_purple_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_purple_200;
			global::MaterialDesignHelpers.Resource.Color.material_purple_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_purple_300;
			global::MaterialDesignHelpers.Resource.Color.material_purple_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_purple_400;
			global::MaterialDesignHelpers.Resource.Color.material_purple_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_purple_50;
			global::MaterialDesignHelpers.Resource.Color.material_purple_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_purple_500;
			global::MaterialDesignHelpers.Resource.Color.material_purple_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_purple_600;
			global::MaterialDesignHelpers.Resource.Color.material_purple_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_purple_700;
			global::MaterialDesignHelpers.Resource.Color.material_purple_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_purple_800;
			global::MaterialDesignHelpers.Resource.Color.material_purple_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_purple_900;
			global::MaterialDesignHelpers.Resource.Color.material_purple_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_purple_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_purple_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_purple_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_purple_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_purple_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_purple_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_purple_accent_700;
			global::MaterialDesignHelpers.Resource.Color.material_red_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_red_100;
			global::MaterialDesignHelpers.Resource.Color.material_red_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_red_200;
			global::MaterialDesignHelpers.Resource.Color.material_red_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_red_300;
			global::MaterialDesignHelpers.Resource.Color.material_red_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_red_400;
			global::MaterialDesignHelpers.Resource.Color.material_red_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_red_50;
			global::MaterialDesignHelpers.Resource.Color.material_red_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_red_500;
			global::MaterialDesignHelpers.Resource.Color.material_red_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_red_600;
			global::MaterialDesignHelpers.Resource.Color.material_red_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_red_700;
			global::MaterialDesignHelpers.Resource.Color.material_red_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_red_800;
			global::MaterialDesignHelpers.Resource.Color.material_red_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_red_900;
			global::MaterialDesignHelpers.Resource.Color.material_red_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_red_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_red_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_red_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_red_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_red_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_red_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_red_accent_700;
			global::MaterialDesignHelpers.Resource.Color.material_teal_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_teal_100;
			global::MaterialDesignHelpers.Resource.Color.material_teal_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_teal_200;
			global::MaterialDesignHelpers.Resource.Color.material_teal_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_teal_300;
			global::MaterialDesignHelpers.Resource.Color.material_teal_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_teal_400;
			global::MaterialDesignHelpers.Resource.Color.material_teal_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_teal_50;
			global::MaterialDesignHelpers.Resource.Color.material_teal_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_teal_500;
			global::MaterialDesignHelpers.Resource.Color.material_teal_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_teal_600;
			global::MaterialDesignHelpers.Resource.Color.material_teal_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_teal_700;
			global::MaterialDesignHelpers.Resource.Color.material_teal_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_teal_800;
			global::MaterialDesignHelpers.Resource.Color.material_teal_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_teal_900;
			global::MaterialDesignHelpers.Resource.Color.material_teal_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_teal_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_teal_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_teal_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_teal_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_teal_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_teal_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_teal_accent_700;
			global::MaterialDesignHelpers.Resource.Color.material_yellow_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_yellow_100;
			global::MaterialDesignHelpers.Resource.Color.material_yellow_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_yellow_200;
			global::MaterialDesignHelpers.Resource.Color.material_yellow_300 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_yellow_300;
			global::MaterialDesignHelpers.Resource.Color.material_yellow_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_yellow_400;
			global::MaterialDesignHelpers.Resource.Color.material_yellow_50 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_yellow_50;
			global::MaterialDesignHelpers.Resource.Color.material_yellow_500 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_yellow_500;
			global::MaterialDesignHelpers.Resource.Color.material_yellow_600 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_yellow_600;
			global::MaterialDesignHelpers.Resource.Color.material_yellow_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_yellow_700;
			global::MaterialDesignHelpers.Resource.Color.material_yellow_800 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_yellow_800;
			global::MaterialDesignHelpers.Resource.Color.material_yellow_900 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_yellow_900;
			global::MaterialDesignHelpers.Resource.Color.material_yellow_accent_100 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_yellow_accent_100;
			global::MaterialDesignHelpers.Resource.Color.material_yellow_accent_200 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_yellow_accent_200;
			global::MaterialDesignHelpers.Resource.Color.material_yellow_accent_400 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_yellow_accent_400;
			global::MaterialDesignHelpers.Resource.Color.material_yellow_accent_700 = global::se.sigcont.android.coffeecalculator.Resource.Color.material_yellow_accent_700;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_bottom_sheet_edge_left_right_margins = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_bottom_sheet_edge_left_right_margins;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_bottom_sheet_edge_top_bottom_margins = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_bottom_sheet_edge_top_bottom_margins;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_bottom_sheet_list_item_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_bottom_sheet_list_item_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_bottom_sheet_list_item_text_horizontal_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_bottom_sheet_list_item_text_horizontal_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_button_corner_radius = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_button_corner_radius;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_button_dense_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_button_dense_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_button_dense_text_size = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_button_dense_text_size;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_button_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_button_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_button_min_width = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_button_min_width;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_button_text_left_and_right_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_button_text_left_and_right_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_button_text_size = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_button_text_size;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_button_touchable_target_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_button_touchable_target_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_cards_action_button_row_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_cards_action_button_row_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_cards_left_and_right_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_cards_left_and_right_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_cards_padding_from_edge_of_screen_to_card = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_cards_padding_from_edge_of_screen_to_card;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_cards_primary_title_bottom_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_cards_primary_title_bottom_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_cards_primary_title_top_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_cards_primary_title_top_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_cards_space_between_cards = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_cards_space_between_cards;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_cards_supporting_text_bottom_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_cards_supporting_text_bottom_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_cards_supporting_text_top_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_cards_supporting_text_top_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_cards_top_and_bottom_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_cards_top_and_bottom_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_dialogs_action_area_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_dialogs_action_area_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_dialogs_elevation = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_dialogs_elevation;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_dialogs_padding_around_buttons = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_dialogs_padding_around_buttons;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_dialogs_padding_around_content_area = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_dialogs_padding_around_content_area;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_dialogs_padding_below_touch_target_to_dialog_edge = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_dialogs_padding_below_touch_target_to_dialog_edge;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_dialogs_padding_between_button_text_right_edge_and_dialog_edge = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_dialogs_padding_between_button_text_right_edge_and_dialog_edge;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_dialogs_padding_between_text_and_touch_target = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_dialogs_padding_between_text_and_touch_target;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_dialogs_padding_between_title_and_body_text = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_dialogs_padding_between_title_and_body_text;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_floating_action_button_margin = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_floating_action_button_margin;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_floating_action_button_mini_size = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_floating_action_button_mini_size;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_floating_action_button_size = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_floating_action_button_size;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_grid_lists_header_footer_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_grid_lists_header_footer_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_grid_lists_header_footer_text_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_grid_lists_header_footer_text_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_grid_lists_header_footer_text_size = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_grid_lists_header_footer_text_size;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_grid_lists_padding_big = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_grid_lists_padding_big;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_grid_lists_padding_small = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_grid_lists_padding_small;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_grid_lists_two_line_header_footer_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_grid_lists_two_line_header_footer_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_lists_icon_left_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_lists_icon_left_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_lists_padding_above_list = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_lists_padding_above_list;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_lists_right_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_lists_right_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_lists_single_line_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_lists_single_line_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_lists_single_line_text_size = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_lists_single_line_text_size;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_lists_single_line_with_avatar_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_lists_single_line_with_avatar_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_lists_text_left_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_lists_text_left_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_lists_text_padding_bottom = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_lists_text_padding_bottom;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_lists_three_line_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_lists_three_line_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_lists_two_line_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_lists_two_line_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_lists_two_line_secondary_text_size = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_lists_two_line_secondary_text_size;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_lists_two_line_text_size = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_lists_two_line_text_size;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_text_fields_floating_label_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_text_fields_floating_label_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_text_fields_floating_label_padding_above_label_text = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_text_fields_floating_label_padding_above_label_text;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_text_fields_floating_label_padding_below_input_text_including_divider = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_text_fields_floating_label_padding_below_input_text_including_divider;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_text_fields_floating_label_padding_below_text_divider = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_text_fields_floating_label_padding_below_text_divider;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_text_fields_floating_label_padding_between_label_and_input_text = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_text_fields_floating_label_padding_between_label_and_input_text;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_text_fields_icon_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_text_fields_icon_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_text_fields_padding_above_and_below_label = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_text_fields_padding_above_and_below_label;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_text_full_width_single_line_text_field_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_text_full_width_single_line_text_field_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_component_text_full_width_single_line_text_field_text_top_and_bottom_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_component_text_full_width_single_line_text_field_text_top_and_bottom_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_app_bar_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_app_bar_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_app_bar_horizontal_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_app_bar_horizontal_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_app_bar_icon_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_app_bar_icon_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_app_bar_title_bottom_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_app_bar_title_bottom_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_app_bar_title_left_padding = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_app_bar_title_left_padding;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_avatar = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_avatar;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_button_height = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_button_height;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_icon = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_icon;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_keylines_content_left_margin_from_screen_edge = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_keylines_content_left_margin_from_screen_edge;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_keylines_horizontal_mobile_margin = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_keylines_horizontal_mobile_margin;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_keylines_screen_edge_margin = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_keylines_screen_edge_margin;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_touch_target = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_touch_target;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_vertical_spacing_between_content_areas = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_vertical_spacing_between_content_areas;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_vertical_spacing_list_item = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_vertical_spacing_list_item;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_vertical_spacing_navigation_right_margin = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_vertical_spacing_navigation_right_margin;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_vertical_spacing_right_side_icons_margin = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_vertical_spacing_right_side_icons_margin;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_vertical_spacing_status_bar = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_vertical_spacing_status_bar;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_vertical_spacing_subtitle = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_vertical_spacing_subtitle;
			global::MaterialDesignHelpers.Resource.Dimension.material_layout_vertical_spacing_tool_bar = global::se.sigcont.android.coffeecalculator.Resource.Dimension.material_layout_vertical_spacing_tool_bar;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0400b7
			public const int material_amber_100 = 2130968759;
			
			// aapt resource value: 0x7f0400b8
			public const int material_amber_200 = 2130968760;
			
			// aapt resource value: 0x7f0400b9
			public const int material_amber_300 = 2130968761;
			
			// aapt resource value: 0x7f0400ba
			public const int material_amber_400 = 2130968762;
			
			// aapt resource value: 0x7f0400b6
			public const int material_amber_50 = 2130968758;
			
			// aapt resource value: 0x7f0400bb
			public const int material_amber_500 = 2130968763;
			
			// aapt resource value: 0x7f0400bc
			public const int material_amber_600 = 2130968764;
			
			// aapt resource value: 0x7f0400bd
			public const int material_amber_700 = 2130968765;
			
			// aapt resource value: 0x7f0400be
			public const int material_amber_800 = 2130968766;
			
			// aapt resource value: 0x7f0400bf
			public const int material_amber_900 = 2130968767;
			
			// aapt resource value: 0x7f0400c0
			public const int material_amber_accent_100 = 2130968768;
			
			// aapt resource value: 0x7f0400c1
			public const int material_amber_accent_200 = 2130968769;
			
			// aapt resource value: 0x7f0400c2
			public const int material_amber_accent_400 = 2130968770;
			
			// aapt resource value: 0x7f0400c3
			public const int material_amber_accent_700 = 2130968771;
			
			// aapt resource value: 0x7f040047
			public const int material_blue_100 = 2130968647;
			
			// aapt resource value: 0x7f040048
			public const int material_blue_200 = 2130968648;
			
			// aapt resource value: 0x7f040049
			public const int material_blue_300 = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public const int material_blue_400 = 2130968650;
			
			// aapt resource value: 0x7f040046
			public const int material_blue_50 = 2130968646;
			
			// aapt resource value: 0x7f04004b
			public const int material_blue_500 = 2130968651;
			
			// aapt resource value: 0x7f04004c
			public const int material_blue_600 = 2130968652;
			
			// aapt resource value: 0x7f04004d
			public const int material_blue_700 = 2130968653;
			
			// aapt resource value: 0x7f04004e
			public const int material_blue_800 = 2130968654;
			
			// aapt resource value: 0x7f04004f
			public const int material_blue_900 = 2130968655;
			
			// aapt resource value: 0x7f040050
			public const int material_blue_accent_100 = 2130968656;
			
			// aapt resource value: 0x7f040051
			public const int material_blue_accent_200 = 2130968657;
			
			// aapt resource value: 0x7f040052
			public const int material_blue_accent_400 = 2130968658;
			
			// aapt resource value: 0x7f040053
			public const int material_blue_accent_700 = 2130968659;
			
			// aapt resource value: 0x7f0400f5
			public const int material_blue_grey_100 = 2130968821;
			
			// aapt resource value: 0x7f0400f6
			public const int material_blue_grey_200 = 2130968822;
			
			// aapt resource value: 0x7f0400f7
			public const int material_blue_grey_300 = 2130968823;
			
			// aapt resource value: 0x7f0400f8
			public const int material_blue_grey_400 = 2130968824;
			
			// aapt resource value: 0x7f0400f4
			public const int material_blue_grey_50 = 2130968820;
			
			// aapt resource value: 0x7f0400f9
			public const int material_blue_grey_500 = 2130968825;
			
			// aapt resource value: 0x7f0400fa
			public const int material_blue_grey_600 = 2130968826;
			
			// aapt resource value: 0x7f0400fb
			public const int material_blue_grey_700 = 2130968827;
			
			// aapt resource value: 0x7f0400fc
			public const int material_blue_grey_800 = 2130968828;
			
			// aapt resource value: 0x7f0400fd
			public const int material_blue_grey_900 = 2130968829;
			
			// aapt resource value: 0x7f0400e1
			public const int material_brown_100 = 2130968801;
			
			// aapt resource value: 0x7f0400e2
			public const int material_brown_200 = 2130968802;
			
			// aapt resource value: 0x7f0400e3
			public const int material_brown_300 = 2130968803;
			
			// aapt resource value: 0x7f0400e4
			public const int material_brown_400 = 2130968804;
			
			// aapt resource value: 0x7f0400e0
			public const int material_brown_50 = 2130968800;
			
			// aapt resource value: 0x7f0400e5
			public const int material_brown_500 = 2130968805;
			
			// aapt resource value: 0x7f0400e6
			public const int material_brown_600 = 2130968806;
			
			// aapt resource value: 0x7f0400e7
			public const int material_brown_700 = 2130968807;
			
			// aapt resource value: 0x7f0400e8
			public const int material_brown_800 = 2130968808;
			
			// aapt resource value: 0x7f0400e9
			public const int material_brown_900 = 2130968809;
			
			// aapt resource value: 0x7f040063
			public const int material_cyan_100 = 2130968675;
			
			// aapt resource value: 0x7f040064
			public const int material_cyan_200 = 2130968676;
			
			// aapt resource value: 0x7f040065
			public const int material_cyan_300 = 2130968677;
			
			// aapt resource value: 0x7f040066
			public const int material_cyan_400 = 2130968678;
			
			// aapt resource value: 0x7f040062
			public const int material_cyan_50 = 2130968674;
			
			// aapt resource value: 0x7f040067
			public const int material_cyan_500 = 2130968679;
			
			// aapt resource value: 0x7f040068
			public const int material_cyan_600 = 2130968680;
			
			// aapt resource value: 0x7f040069
			public const int material_cyan_700 = 2130968681;
			
			// aapt resource value: 0x7f04006a
			public const int material_cyan_800 = 2130968682;
			
			// aapt resource value: 0x7f04006b
			public const int material_cyan_900 = 2130968683;
			
			// aapt resource value: 0x7f04006c
			public const int material_cyan_accent_100 = 2130968684;
			
			// aapt resource value: 0x7f04006d
			public const int material_cyan_accent_200 = 2130968685;
			
			// aapt resource value: 0x7f04006e
			public const int material_cyan_accent_400 = 2130968686;
			
			// aapt resource value: 0x7f04006f
			public const int material_cyan_accent_700 = 2130968687;
			
			// aapt resource value: 0x7f0400d3
			public const int material_deep_orange_100 = 2130968787;
			
			// aapt resource value: 0x7f0400d4
			public const int material_deep_orange_200 = 2130968788;
			
			// aapt resource value: 0x7f0400d5
			public const int material_deep_orange_300 = 2130968789;
			
			// aapt resource value: 0x7f0400d6
			public const int material_deep_orange_400 = 2130968790;
			
			// aapt resource value: 0x7f0400d2
			public const int material_deep_orange_50 = 2130968786;
			
			// aapt resource value: 0x7f0400d7
			public const int material_deep_orange_500 = 2130968791;
			
			// aapt resource value: 0x7f0400d8
			public const int material_deep_orange_600 = 2130968792;
			
			// aapt resource value: 0x7f0400d9
			public const int material_deep_orange_700 = 2130968793;
			
			// aapt resource value: 0x7f0400da
			public const int material_deep_orange_800 = 2130968794;
			
			// aapt resource value: 0x7f0400db
			public const int material_deep_orange_900 = 2130968795;
			
			// aapt resource value: 0x7f0400dc
			public const int material_deep_orange_accent_100 = 2130968796;
			
			// aapt resource value: 0x7f0400dd
			public const int material_deep_orange_accent_200 = 2130968797;
			
			// aapt resource value: 0x7f0400de
			public const int material_deep_orange_accent_400 = 2130968798;
			
			// aapt resource value: 0x7f0400df
			public const int material_deep_orange_accent_700 = 2130968799;
			
			// aapt resource value: 0x7f04002b
			public const int material_deep_purple_100 = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int material_deep_purple_200 = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int material_deep_purple_300 = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int material_deep_purple_400 = 2130968622;
			
			// aapt resource value: 0x7f04002a
			public const int material_deep_purple_50 = 2130968618;
			
			// aapt resource value: 0x7f04002f
			public const int material_deep_purple_500 = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int material_deep_purple_600 = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int material_deep_purple_700 = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int material_deep_purple_800 = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int material_deep_purple_900 = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int material_deep_purple_accent_100 = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int material_deep_purple_accent_200 = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int material_deep_purple_accent_400 = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int material_deep_purple_accent_700 = 2130968631;
			
			// aapt resource value: 0x7f04007f
			public const int material_green_100 = 2130968703;
			
			// aapt resource value: 0x7f040080
			public const int material_green_200 = 2130968704;
			
			// aapt resource value: 0x7f040081
			public const int material_green_300 = 2130968705;
			
			// aapt resource value: 0x7f040082
			public const int material_green_400 = 2130968706;
			
			// aapt resource value: 0x7f04007e
			public const int material_green_50 = 2130968702;
			
			// aapt resource value: 0x7f040083
			public const int material_green_500 = 2130968707;
			
			// aapt resource value: 0x7f040084
			public const int material_green_600 = 2130968708;
			
			// aapt resource value: 0x7f040085
			public const int material_green_700 = 2130968709;
			
			// aapt resource value: 0x7f040086
			public const int material_green_800 = 2130968710;
			
			// aapt resource value: 0x7f040087
			public const int material_green_900 = 2130968711;
			
			// aapt resource value: 0x7f040088
			public const int material_green_accent_100 = 2130968712;
			
			// aapt resource value: 0x7f040089
			public const int material_green_accent_200 = 2130968713;
			
			// aapt resource value: 0x7f04008a
			public const int material_green_accent_400 = 2130968714;
			
			// aapt resource value: 0x7f04008b
			public const int material_green_accent_700 = 2130968715;
			
			// aapt resource value: 0x7f0400eb
			public const int material_grey_100 = 2130968811;
			
			// aapt resource value: 0x7f0400ec
			public const int material_grey_200 = 2130968812;
			
			// aapt resource value: 0x7f0400ed
			public const int material_grey_300 = 2130968813;
			
			// aapt resource value: 0x7f0400ee
			public const int material_grey_400 = 2130968814;
			
			// aapt resource value: 0x7f0400ea
			public const int material_grey_50 = 2130968810;
			
			// aapt resource value: 0x7f0400ef
			public const int material_grey_500 = 2130968815;
			
			// aapt resource value: 0x7f0400f0
			public const int material_grey_600 = 2130968816;
			
			// aapt resource value: 0x7f0400f1
			public const int material_grey_700 = 2130968817;
			
			// aapt resource value: 0x7f0400f2
			public const int material_grey_800 = 2130968818;
			
			// aapt resource value: 0x7f0400f3
			public const int material_grey_900 = 2130968819;
			
			// aapt resource value: 0x7f040039
			public const int material_indigo_100 = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int material_indigo_200 = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int material_indigo_300 = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int material_indigo_400 = 2130968636;
			
			// aapt resource value: 0x7f040038
			public const int material_indigo_50 = 2130968632;
			
			// aapt resource value: 0x7f04003d
			public const int material_indigo_500 = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int material_indigo_600 = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int material_indigo_700 = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int material_indigo_800 = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int material_indigo_900 = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int material_indigo_accent_100 = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int material_indigo_accent_200 = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int material_indigo_accent_400 = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int material_indigo_accent_700 = 2130968645;
			
			// aapt resource value: 0x7f0400fe
			public const int material_light_black = 2130968830;
			
			// aapt resource value: 0x7f040055
			public const int material_light_blue_100 = 2130968661;
			
			// aapt resource value: 0x7f040056
			public const int material_light_blue_200 = 2130968662;
			
			// aapt resource value: 0x7f040057
			public const int material_light_blue_300 = 2130968663;
			
			// aapt resource value: 0x7f040058
			public const int material_light_blue_400 = 2130968664;
			
			// aapt resource value: 0x7f040054
			public const int material_light_blue_50 = 2130968660;
			
			// aapt resource value: 0x7f040059
			public const int material_light_blue_500 = 2130968665;
			
			// aapt resource value: 0x7f04005a
			public const int material_light_blue_600 = 2130968666;
			
			// aapt resource value: 0x7f04005b
			public const int material_light_blue_700 = 2130968667;
			
			// aapt resource value: 0x7f04005c
			public const int material_light_blue_800 = 2130968668;
			
			// aapt resource value: 0x7f04005d
			public const int material_light_blue_900 = 2130968669;
			
			// aapt resource value: 0x7f04005e
			public const int material_light_blue_accent_100 = 2130968670;
			
			// aapt resource value: 0x7f04005f
			public const int material_light_blue_accent_200 = 2130968671;
			
			// aapt resource value: 0x7f040060
			public const int material_light_blue_accent_400 = 2130968672;
			
			// aapt resource value: 0x7f040061
			public const int material_light_blue_accent_700 = 2130968673;
			
			// aapt resource value: 0x7f04008d
			public const int material_light_green_100 = 2130968717;
			
			// aapt resource value: 0x7f04008e
			public const int material_light_green_200 = 2130968718;
			
			// aapt resource value: 0x7f04008f
			public const int material_light_green_300 = 2130968719;
			
			// aapt resource value: 0x7f040090
			public const int material_light_green_400 = 2130968720;
			
			// aapt resource value: 0x7f04008c
			public const int material_light_green_50 = 2130968716;
			
			// aapt resource value: 0x7f040091
			public const int material_light_green_500 = 2130968721;
			
			// aapt resource value: 0x7f040092
			public const int material_light_green_600 = 2130968722;
			
			// aapt resource value: 0x7f040093
			public const int material_light_green_700 = 2130968723;
			
			// aapt resource value: 0x7f040094
			public const int material_light_green_800 = 2130968724;
			
			// aapt resource value: 0x7f040095
			public const int material_light_green_900 = 2130968725;
			
			// aapt resource value: 0x7f040096
			public const int material_light_green_accent_100 = 2130968726;
			
			// aapt resource value: 0x7f040097
			public const int material_light_green_accent_200 = 2130968727;
			
			// aapt resource value: 0x7f040098
			public const int material_light_green_accent_400 = 2130968728;
			
			// aapt resource value: 0x7f040099
			public const int material_light_green_accent_700 = 2130968729;
			
			// aapt resource value: 0x7f0400ff
			public const int material_light_white = 2130968831;
			
			// aapt resource value: 0x7f04009b
			public const int material_lime_100 = 2130968731;
			
			// aapt resource value: 0x7f04009c
			public const int material_lime_200 = 2130968732;
			
			// aapt resource value: 0x7f04009d
			public const int material_lime_300 = 2130968733;
			
			// aapt resource value: 0x7f04009e
			public const int material_lime_400 = 2130968734;
			
			// aapt resource value: 0x7f04009a
			public const int material_lime_50 = 2130968730;
			
			// aapt resource value: 0x7f04009f
			public const int material_lime_500 = 2130968735;
			
			// aapt resource value: 0x7f0400a0
			public const int material_lime_600 = 2130968736;
			
			// aapt resource value: 0x7f0400a1
			public const int material_lime_700 = 2130968737;
			
			// aapt resource value: 0x7f0400a2
			public const int material_lime_800 = 2130968738;
			
			// aapt resource value: 0x7f0400a3
			public const int material_lime_900 = 2130968739;
			
			// aapt resource value: 0x7f0400a4
			public const int material_lime_accent_100 = 2130968740;
			
			// aapt resource value: 0x7f0400a5
			public const int material_lime_accent_200 = 2130968741;
			
			// aapt resource value: 0x7f0400a6
			public const int material_lime_accent_400 = 2130968742;
			
			// aapt resource value: 0x7f0400a7
			public const int material_lime_accent_700 = 2130968743;
			
			// aapt resource value: 0x7f0400c5
			public const int material_orange_100 = 2130968773;
			
			// aapt resource value: 0x7f0400c6
			public const int material_orange_200 = 2130968774;
			
			// aapt resource value: 0x7f0400c7
			public const int material_orange_300 = 2130968775;
			
			// aapt resource value: 0x7f0400c8
			public const int material_orange_400 = 2130968776;
			
			// aapt resource value: 0x7f0400c4
			public const int material_orange_50 = 2130968772;
			
			// aapt resource value: 0x7f0400c9
			public const int material_orange_500 = 2130968777;
			
			// aapt resource value: 0x7f0400ca
			public const int material_orange_600 = 2130968778;
			
			// aapt resource value: 0x7f0400cb
			public const int material_orange_700 = 2130968779;
			
			// aapt resource value: 0x7f0400cc
			public const int material_orange_800 = 2130968780;
			
			// aapt resource value: 0x7f0400cd
			public const int material_orange_900 = 2130968781;
			
			// aapt resource value: 0x7f0400ce
			public const int material_orange_accent_100 = 2130968782;
			
			// aapt resource value: 0x7f0400cf
			public const int material_orange_accent_200 = 2130968783;
			
			// aapt resource value: 0x7f0400d0
			public const int material_orange_accent_400 = 2130968784;
			
			// aapt resource value: 0x7f0400d1
			public const int material_orange_accent_700 = 2130968785;
			
			// aapt resource value: 0x7f04000f
			public const int material_pink_100 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int material_pink_200 = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int material_pink_300 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int material_pink_400 = 2130968594;
			
			// aapt resource value: 0x7f04000e
			public const int material_pink_50 = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int material_pink_500 = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int material_pink_600 = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int material_pink_700 = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int material_pink_800 = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int material_pink_900 = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int material_pink_accent_100 = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int material_pink_accent_200 = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int material_pink_accent_400 = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int material_pink_accent_700 = 2130968603;
			
			// aapt resource value: 0x7f04001d
			public const int material_purple_100 = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int material_purple_200 = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int material_purple_300 = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int material_purple_400 = 2130968608;
			
			// aapt resource value: 0x7f04001c
			public const int material_purple_50 = 2130968604;
			
			// aapt resource value: 0x7f040021
			public const int material_purple_500 = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int material_purple_600 = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int material_purple_700 = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int material_purple_800 = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int material_purple_900 = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int material_purple_accent_100 = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int material_purple_accent_200 = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int material_purple_accent_400 = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int material_purple_accent_700 = 2130968617;
			
			// aapt resource value: 0x7f040001
			public const int material_red_100 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int material_red_200 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int material_red_300 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int material_red_400 = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int material_red_50 = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int material_red_500 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int material_red_600 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int material_red_700 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int material_red_800 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int material_red_900 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int material_red_accent_100 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int material_red_accent_200 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int material_red_accent_400 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int material_red_accent_700 = 2130968589;
			
			// aapt resource value: 0x7f040071
			public const int material_teal_100 = 2130968689;
			
			// aapt resource value: 0x7f040072
			public const int material_teal_200 = 2130968690;
			
			// aapt resource value: 0x7f040073
			public const int material_teal_300 = 2130968691;
			
			// aapt resource value: 0x7f040074
			public const int material_teal_400 = 2130968692;
			
			// aapt resource value: 0x7f040070
			public const int material_teal_50 = 2130968688;
			
			// aapt resource value: 0x7f040075
			public const int material_teal_500 = 2130968693;
			
			// aapt resource value: 0x7f040076
			public const int material_teal_600 = 2130968694;
			
			// aapt resource value: 0x7f040077
			public const int material_teal_700 = 2130968695;
			
			// aapt resource value: 0x7f040078
			public const int material_teal_800 = 2130968696;
			
			// aapt resource value: 0x7f040079
			public const int material_teal_900 = 2130968697;
			
			// aapt resource value: 0x7f04007a
			public const int material_teal_accent_100 = 2130968698;
			
			// aapt resource value: 0x7f04007b
			public const int material_teal_accent_200 = 2130968699;
			
			// aapt resource value: 0x7f04007c
			public const int material_teal_accent_400 = 2130968700;
			
			// aapt resource value: 0x7f04007d
			public const int material_teal_accent_700 = 2130968701;
			
			// aapt resource value: 0x7f0400a9
			public const int material_yellow_100 = 2130968745;
			
			// aapt resource value: 0x7f0400aa
			public const int material_yellow_200 = 2130968746;
			
			// aapt resource value: 0x7f0400ab
			public const int material_yellow_300 = 2130968747;
			
			// aapt resource value: 0x7f0400ac
			public const int material_yellow_400 = 2130968748;
			
			// aapt resource value: 0x7f0400a8
			public const int material_yellow_50 = 2130968744;
			
			// aapt resource value: 0x7f0400ad
			public const int material_yellow_500 = 2130968749;
			
			// aapt resource value: 0x7f0400ae
			public const int material_yellow_600 = 2130968750;
			
			// aapt resource value: 0x7f0400af
			public const int material_yellow_700 = 2130968751;
			
			// aapt resource value: 0x7f0400b0
			public const int material_yellow_800 = 2130968752;
			
			// aapt resource value: 0x7f0400b1
			public const int material_yellow_900 = 2130968753;
			
			// aapt resource value: 0x7f0400b2
			public const int material_yellow_accent_100 = 2130968754;
			
			// aapt resource value: 0x7f0400b3
			public const int material_yellow_accent_200 = 2130968755;
			
			// aapt resource value: 0x7f0400b4
			public const int material_yellow_accent_400 = 2130968756;
			
			// aapt resource value: 0x7f0400b5
			public const int material_yellow_accent_700 = 2130968757;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050013
			public const int material_component_bottom_sheet_edge_left_right_margins = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int material_component_bottom_sheet_edge_top_bottom_margins = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int material_component_bottom_sheet_list_item_height = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int material_component_bottom_sheet_list_item_text_horizontal_padding = 2131034134;
			
			// aapt resource value: 0x7f05001b
			public const int material_component_button_corner_radius = 2131034139;
			
			// aapt resource value: 0x7f050018
			public const int material_component_button_dense_height = 2131034136;
			
			// aapt resource value: 0x7f05001e
			public const int material_component_button_dense_text_size = 2131034142;
			
			// aapt resource value: 0x7f050017
			public const int material_component_button_height = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int material_component_button_min_width = 2131034137;
			
			// aapt resource value: 0x7f05001c
			public const int material_component_button_text_left_and_right_padding = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int material_component_button_text_size = 2131034141;
			
			// aapt resource value: 0x7f05001a
			public const int material_component_button_touchable_target_height = 2131034138;
			
			// aapt resource value: 0x7f050024
			public const int material_component_cards_action_button_row_padding = 2131034148;
			
			// aapt resource value: 0x7f050027
			public const int material_component_cards_left_and_right_padding = 2131034151;
			
			// aapt resource value: 0x7f050029
			public const int material_component_cards_padding_from_edge_of_screen_to_card = 2131034153;
			
			// aapt resource value: 0x7f050023
			public const int material_component_cards_primary_title_bottom_padding = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int material_component_cards_primary_title_top_padding = 2131034146;
			
			// aapt resource value: 0x7f05002a
			public const int material_component_cards_space_between_cards = 2131034154;
			
			// aapt resource value: 0x7f050026
			public const int material_component_cards_supporting_text_bottom_padding = 2131034150;
			
			// aapt resource value: 0x7f050025
			public const int material_component_cards_supporting_text_top_padding = 2131034149;
			
			// aapt resource value: 0x7f050028
			public const int material_component_cards_top_and_bottom_padding = 2131034152;
			
			// aapt resource value: 0x7f05002e
			public const int material_component_dialogs_action_area_height = 2131034158;
			
			// aapt resource value: 0x7f050030
			public const int material_component_dialogs_elevation = 2131034160;
			
			// aapt resource value: 0x7f05002d
			public const int material_component_dialogs_padding_around_buttons = 2131034157;
			
			// aapt resource value: 0x7f05002b
			public const int material_component_dialogs_padding_around_content_area = 2131034155;
			
			// aapt resource value: 0x7f050031
			public const int material_component_dialogs_padding_below_touch_target_to_dialog_edge = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int material_component_dialogs_padding_between_button_text_right_edge_and_dialog_edge = 2131034162;
			
			// aapt resource value: 0x7f05002f
			public const int material_component_dialogs_padding_between_text_and_touch_target = 2131034159;
			
			// aapt resource value: 0x7f05002c
			public const int material_component_dialogs_padding_between_title_and_body_text = 2131034156;
			
			// aapt resource value: 0x7f05001f
			public const int material_component_floating_action_button_margin = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int material_component_floating_action_button_mini_size = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int material_component_floating_action_button_size = 2131034144;
			
			// aapt resource value: 0x7f050033
			public const int material_component_grid_lists_header_footer_height = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int material_component_grid_lists_header_footer_text_padding = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int material_component_grid_lists_header_footer_text_size = 2131034165;
			
			// aapt resource value: 0x7f050037
			public const int material_component_grid_lists_padding_big = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int material_component_grid_lists_padding_small = 2131034168;
			
			// aapt resource value: 0x7f050036
			public const int material_component_grid_lists_two_line_header_footer_height = 2131034166;
			
			// aapt resource value: 0x7f050039
			public const int material_component_lists_icon_left_padding = 2131034169;
			
			// aapt resource value: 0x7f05003d
			public const int material_component_lists_padding_above_list = 2131034173;
			
			// aapt resource value: 0x7f05003b
			public const int material_component_lists_right_padding = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int material_component_lists_single_line_height = 2131034172;
			
			// aapt resource value: 0x7f05003f
			public const int material_component_lists_single_line_text_size = 2131034175;
			
			// aapt resource value: 0x7f05003e
			public const int material_component_lists_single_line_with_avatar_height = 2131034174;
			
			// aapt resource value: 0x7f05003a
			public const int material_component_lists_text_left_padding = 2131034170;
			
			// aapt resource value: 0x7f050044
			public const int material_component_lists_text_padding_bottom = 2131034180;
			
			// aapt resource value: 0x7f050043
			public const int material_component_lists_three_line_height = 2131034179;
			
			// aapt resource value: 0x7f050040
			public const int material_component_lists_two_line_height = 2131034176;
			
			// aapt resource value: 0x7f050042
			public const int material_component_lists_two_line_secondary_text_size = 2131034178;
			
			// aapt resource value: 0x7f050041
			public const int material_component_lists_two_line_text_size = 2131034177;
			
			// aapt resource value: 0x7f050045
			public const int material_component_text_fields_floating_label_height = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int material_component_text_fields_floating_label_padding_above_label_text = 2131034182;
			
			// aapt resource value: 0x7f050048
			public const int material_component_text_fields_floating_label_padding_below_input_text_including_divider = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int material_component_text_fields_floating_label_padding_below_text_divider = 2131034185;
			
			// aapt resource value: 0x7f050047
			public const int material_component_text_fields_floating_label_padding_between_label_and_input_text = 2131034183;
			
			// aapt resource value: 0x7f05004a
			public const int material_component_text_fields_icon_height = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int material_component_text_fields_padding_above_and_below_label = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int material_component_text_full_width_single_line_text_field_height = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int material_component_text_full_width_single_line_text_field_text_top_and_bottom_padding = 2131034189;
			
			// aapt resource value: 0x7f05000e
			public const int material_layout_app_bar_height = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int material_layout_app_bar_horizontal_padding = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int material_layout_app_bar_icon_padding = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int material_layout_app_bar_title_bottom_padding = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int material_layout_app_bar_title_left_padding = 2131034129;
			
			// aapt resource value: 0x7f05000a
			public const int material_layout_avatar = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int material_layout_button_height = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int material_layout_icon = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int material_layout_keylines_content_left_margin_from_screen_edge = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int material_layout_keylines_horizontal_mobile_margin = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int material_layout_keylines_screen_edge_margin = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int material_layout_touch_target = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int material_layout_vertical_spacing_between_content_areas = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int material_layout_vertical_spacing_list_item = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int material_layout_vertical_spacing_navigation_right_margin = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int material_layout_vertical_spacing_right_side_icons_margin = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int material_layout_vertical_spacing_status_bar = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int material_layout_vertical_spacing_subtitle = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int material_layout_vertical_spacing_tool_bar = 2131034116;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int MyButton = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
